name: build-test

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install
        shell: bash
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
